# Generated by Django 5.2.9 on 2026-01-10 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0002_remove_employeeprofile_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeeprofile',
            name='employee_id',
            field=models.CharField(blank=True, editable=False, max_length=50, null=True, unique=True),
        ),
    ]
