# Generated by Django 5.2.9 on 2026-01-02 13:50

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AnalyticsCache',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cache_key', models.CharField(max_length=255, unique=True)),
                ('cache_type', models.CharField(choices=[('EMPLOYEE_PRODUCTIVITY', 'Employee Productivity'), ('DEPARTMENT_METRICS', 'Department Metrics'), ('TASK_TRENDS', 'Task Trends')], max_length=30)),
                ('data', models.JSONField()),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('expires_at', models.DateTimeField()),
            ],
            options={
                'indexes': [models.Index(fields=['cache_type', 'expires_at'], name='analytics_a_cache_t_94d7b2_idx')],
            },
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('report_type', models.CharField(choices=[('PRODUCTIVITY', 'Productivity Report'), ('DEPARTMENT', 'Department Analytics'), ('TASK_TRENDS', 'Task Trends'), ('OVERDUE', 'Overdue Analysis')], max_length=20)),
                ('generated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('data', models.JSONField()),
                ('filters', models.JSONField(blank=True, null=True)),
                ('generated_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-generated_at'],
            },
        ),
        migrations.CreateModel(
            name='KPI',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('value', models.FloatField()),
                ('department', models.CharField(blank=True, max_length=255)),
                ('calculated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('period_start', models.DateField()),
                ('period_end', models.DateField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kpis', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['user', 'period_start', 'period_end'], name='analytics_k_user_id_d059f9_idx'), models.Index(fields=['department', 'period_start', 'period_end'], name='analytics_k_departm_99523b_idx')],
            },
        ),
    ]
