# Generated by Django 5.2.9 on 2026-01-02 13:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
        ('tasks', '0002_timelog'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='notification',
            options={},
        ),
        migrations.RemoveField(
            model_name='notification',
            name='related_submission',
        ),
        migrations.RemoveField(
            model_name='notification',
            name='related_task',
        ),
        migrations.RemoveField(
            model_name='notification',
            name='title',
        ),
        migrations.AddField(
            model_name='notification',
            name='task',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tasks.task'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('ASSIGNMENT', 'Task Assignment'), ('DUE_REMINDER', 'Due Date Reminder'), ('SUBMISSION_CONFIRM', 'Submission Confirmation'), ('REVIEW', 'Submission Review')], default='ASSIGNMENT', max_length=20),
        ),
    ]
